(function () {
    var myChart = echarts.init(document.querySelector("#myChart"));
    var option = {
        backgroundColor: new echarts.graphic.RadialGradient(0.3, 0.3, 0.8, [{
            offset: 0,
            color: 'rgba(238,209,147,0)'
        }, {
            offset: 1,
            color: 'rgba(238,163,86,0)'
        }]),
        title: {
            text: "药\n膳\n功\n效\n图",
            top: '25%',
            left: 0,
            textStyle: {
                fontSize: 20,
                fontFamily: 'Arial, sans-serif',
                verticalAlign: 'top',
                lineHeight: 20,

            },
        },
        tooltip: {},
        legend: [{
            formatter: function (name) {
                return echarts.format.truncateText(name, 40, '14px Microsoft Yahei', '…');
            },
            tooltip: {
                show: true
            },
            selectedMode: 'false',
            bottom: 0,
            data: ['滋阴', '益肝', '补气', '固肾', '润肺', '清热', '补肾', '利水', '补脾', '利湿', '理气', '益胃', '养心', '健脾', '益气', '补肝', '强筋', '活血', '益肾', '养血', '益精', '止咳', '解毒', '壮阳', '消肿', '健胃', '利尿', '润燥', '消食', '养阴', '安神', '化痰', '养胃', '壮骨', '免疫', '温胃', '化瘀', '补血', '益肺', '调理', '明目', '补虚', '开胃', '固精', '祛痰', '生津', '强身', '和胃', '健骨']
        }],

        toolbox: {
            show: true,
            feature: {
                dataView: {
                    show: true,
                    readOnly: true
                },
                restore: {
                    show: true
                },
                saveAsImage: {
                    show: true
                }
            }
        },
        animationDuration: 3000,
        animationEasingUpdate: 'quinticInOut',
        series: [{

            name: '药膳',
            type: 'graph',
            layout: 'force',

            force: {
                repulsion: 1000
            },
            data: [{
                "name": "药膳",
                // "x": 0,
                // y: 0,
                "symbolSize": 100,
                "draggable": "true",
                "value": 99

            },
            { 'name': '淮山党参鹌鹑汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '五指毛桃煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 3, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '客家娘酒煲母鸡', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '山萸肉芡实煲瘦肉', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '百合西洋菜猪展生鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '清补凉乳鸽汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '独脚金煲瘦肉', 'symbolSize': 5, 'draggable': 'true', 'value': 3, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '太子参无花果瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '春砂仁煲猪肚', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '春砂仁煲鲫鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '栗子淮山猪蹄汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '白菜干豆腐腊鸭头汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '粉葛煲鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '猪笼草赤小豆横脷汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '浮小麦参淮牛展汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '绵茵陈煲鲫鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '金婴子泽泻煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '陈皮炖老鸭', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '木瓜煲老鸭', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '淮山沙参玉竹鹅肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '黑豆鲤鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '百合陈皮鲫鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '南北杏煲鳄鱼肉', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '木瓜墨鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '糯稻根煲山斑鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '豆角干煲鲩鱼尾', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '糯稻根太子参煲泥鳅鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '云苓黄精生蚝汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '双仁炖猪心汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '大地鱼瘦肉滚豆腐汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '沙参玉竹薏仁猪脚筋汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '雪梨麻黄瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '苹果雪耳瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '鲜橄榄煲海螺瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '龙利叶黄豆炖白鲫鱼', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '冬虫草炖水鸭', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '猴头菇白果鲨鱼骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '黄豆蚝豉排骨苦瓜汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '红罗卜排骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '鲜莲子滚鸡肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 5, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '西洋参淮山红枣清炖乳鸽', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '绿豆百合炖白鸽', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '花生北芪红枣煲牛展', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '荷花荔枝干炖老鸭', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '石斛淮山杞子猪骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '石斛冰糖茶', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '石斛麦冬瘦肉汽', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '石斛太子参煲瘦肉', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '明目补肝汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '石斛杞子猪肝汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '清炖蚌肉', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '松子仁煲西洋参鲜鸡汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '橄榄响螺瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '鲜茅根霸王花猪肺汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '蜜枣淮山西施骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '灵芝煲猪肚', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '杞子滚牛肝汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '使君子煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '石斛玉竹沙参煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '椰子黄豆无花果田鸡汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '猫爪草煲瘦肉', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '杜仲补骨脂排骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '淮山元肉炖水鱼', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '眉豆花生玉米煲山斑鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '无花果花生煲猪肚汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '榴莲芯煲鲫鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '淮山莲子煲海龙', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '党参百合煲猪肺', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '毛冬青杞子菟丝子煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '西红柿滚咸猪肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '川贝北杏炖鳄鱼肉', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '猫爪草夏枯草煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '沙榄去耳煲猪展汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '灵芝圆肉煲瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '西洋参石斛淮山煲鸡', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '竹蔗红罗卜猪骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '党参百合猪肺', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '芡实江珧柱猪粉肠汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '莲藕鲤鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '川贝枇杷叶炖鳄鱼肉瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '丹参四鸡炖冰糖', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '栗子莲子猪腰汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '鸭梨北杏鹅肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '浮小麦黑豆生蚝汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '核桃淮山芡实猪展汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '黄芪南枣黄鳝汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '无花果茶树菇山鸡汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '芋干瘦肉汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '原盅炖北菇', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '杜仲肉菘蓉煲猪骨汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '莲藕红豆白鸽汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '新鲜霸王花猪展汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '核桃淡菜番鸭汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '党参北芪茨实淮山煲瘦肉/山斑鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '萝卜滚鳕鱼汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '白果枝竹冬瓜老鸭汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '蜜瓜海螺老鸡汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '冬虫草珧柱猪展汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },
            { 'name': '眉豆花生红枣猪尾汤', 'symbolSize': 5, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(0,0,0)' }, label: { show: false }, emphasis: { label: { show: true } } },

            { 'name': '滋阴', 'symbolSize': 60, 'draggable': 'true', 'value': 41, 'itemStyle': { 'color': 'rgb(90,121,4)' } },
            { 'name': '益肝', 'symbolSize': 60, 'draggable': 'true', 'value': 2, 'itemStyle': { 'color': 'rgb(68,106,187)' } },
            { 'name': '补气', 'symbolSize': 60, 'draggable': 'true', 'value': 14, 'itemStyle': { 'color': 'rgb(88,220,135)' } },
            { 'name': '固肾', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(101,88,42)' } },
            { 'name': '润肺', 'symbolSize': 60, 'draggable': 'true', 'value': 38, 'itemStyle': { 'color': 'rgb(122,165,248)' } },
            { 'name': '清热', 'symbolSize': 60, 'draggable': 'true', 'value': 31, 'itemStyle': { 'color': 'rgb(255,18,90)' } },
            { 'name': '补肾', 'symbolSize': 60, 'draggable': 'true', 'value': 16, 'itemStyle': { 'color': 'rgb(16,17,79)' } },
            { 'name': '利水', 'symbolSize': 60, 'draggable': 'true', 'value': 12, 'itemStyle': { 'color': 'rgb(75,169,162)' } },
            { 'name': '补脾', 'symbolSize': 60, 'draggable': 'true', 'value': 8, 'itemStyle': { 'color': 'rgb(114,131,25)' } },
            { 'name': '利湿', 'symbolSize': 60, 'draggable': 'true', 'value': 5, 'itemStyle': { 'color': 'rgb(205,49,154)' } },
            { 'name': '理气', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(76,124,20)' } },
            { 'name': '益胃', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(75,59,6)' } },
            { 'name': '养心', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(17,73,149)' } },
            { 'name': '健脾', 'symbolSize': 60, 'draggable': 'true', 'value': 29, 'itemStyle': { 'color': 'rgb(175,41,41)' } },
            { 'name': '益气', 'symbolSize': 60, 'draggable': 'true', 'value': 15, 'itemStyle': { 'color': 'rgb(222,163,219)' } },
            { 'name': '补肝', 'symbolSize': 60, 'draggable': 'true', 'value': 2, 'itemStyle': { 'color': 'rgb(214,89,51)' } },
            { 'name': '强筋', 'symbolSize': 60, 'draggable': 'true', 'value': 2, 'itemStyle': { 'color': 'rgb(82,69,226)' } },
            { 'name': '活血', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(25,49,93)' } },
            { 'name': '益肾', 'symbolSize': 60, 'draggable': 'true', 'value': 19, 'itemStyle': { 'color': 'rgb(47,151,69)' } },
            { 'name': '养血', 'symbolSize': 60, 'draggable': 'true', 'value': 28, 'itemStyle': { 'color': 'rgb(4,54,25)' } },
            { 'name': '益精', 'symbolSize': 60, 'draggable': 'true', 'value': 11, 'itemStyle': { 'color': 'rgb(126,12,108)' } },
            { 'name': '止咳', 'symbolSize': 60, 'draggable': 'true', 'value': 18, 'itemStyle': { 'color': 'rgb(34,181,139)' } },
            { 'name': '解毒', 'symbolSize': 60, 'draggable': 'true', 'value': 23, 'itemStyle': { 'color': 'rgb(136,94,36)' } },
            { 'name': '壮阳', 'symbolSize': 60, 'draggable': 'true', 'value': 9, 'itemStyle': { 'color': 'rgb(121,128,133)' } },
            { 'name': '消肿', 'symbolSize': 60, 'draggable': 'true', 'value': 11, 'itemStyle': { 'color': 'rgb(76,181,36)' } },
            { 'name': '健胃', 'symbolSize': 60, 'draggable': 'true', 'value': 4, 'itemStyle': { 'color': 'rgb(93,33,145)' } },
            { 'name': '利尿', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(185,153,251)' } },
            { 'name': '润燥', 'symbolSize': 60, 'draggable': 'true', 'value': 8, 'itemStyle': { 'color': 'rgb(34,84,140)' } },
            { 'name': '消食', 'symbolSize': 60, 'draggable': 'true', 'value': 5, 'itemStyle': { 'color': 'rgb(248,94,159)' } },
            { 'name': '养阴', 'symbolSize': 60, 'draggable': 'true', 'value': 3, 'itemStyle': { 'color': 'rgb(90,4,193)' } },
            { 'name': '安神', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(56,35,7)' } },
            { 'name': '化痰', 'symbolSize': 60, 'draggable': 'true', 'value': 5, 'itemStyle': { 'color': 'rgb(159,158,54)' } },
            { 'name': '养胃', 'symbolSize': 60, 'draggable': 'true', 'value': 3, 'itemStyle': { 'color': 'rgb(54,117,51)' } },
            { 'name': '壮骨', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(134,115,226)' } },
            { 'name': '免疫', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(56,77,71)' } },
            { 'name': '温胃', 'symbolSize': 60, 'draggable': 'true', 'value': 3, 'itemStyle': { 'color': 'rgb(15,196,221)' } },
            { 'name': '化瘀', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(217,14,122)' } },
            { 'name': '补血', 'symbolSize': 60, 'draggable': 'true', 'value': 2, 'itemStyle': { 'color': 'rgb(69,11,86)' } },
            { 'name': '益肺', 'symbolSize': 60, 'draggable': 'true', 'value': 3, 'itemStyle': { 'color': 'rgb(8,45,96)' } },
            { 'name': '明目', 'symbolSize': 60, 'draggable': 'true', 'value': 2, 'itemStyle': { 'color': 'rgb(215,104,11)' } },
            { 'name': '补虚', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(148,94,173)' } },
            { 'name': '开胃', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(170,127,67)' } },
            { 'name': '固精', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(114,56,95)' } },
            { 'name': '祛痰', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(213,156,241)' } },
            { 'name': '生津', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(11,225,53)' } },
            { 'name': '强身', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(69,73,31)' } },
            { 'name': '和胃', 'symbolSize': 60, 'draggable': 'true', 'value': 2, 'itemStyle': { 'color': 'rgb(118,100,173)' } },
            { 'name': '健骨', 'symbolSize': 60, 'draggable': 'true', 'value': 1, 'itemStyle': { 'color': 'rgb(224,75,27)' } }







            ],

            links: [{ "source": "药膳", "target": "滋阴" },
            { "source": "药膳", "target": "益肝" },
            { "source": "药膳", "target": "补气" },
            { "source": "药膳", "target": "固肾" },
            { "source": "药膳", "target": "润肺" },
            { "source": "药膳", "target": "清热" },
            { "source": "药膳", "target": "补肾" },
            { "source": "药膳", "target": "利水" },
            { "source": "药膳", "target": "补脾" },
            { "source": "药膳", "target": "利湿" },
            { "source": "药膳", "target": "理气" },
            { "source": "药膳", "target": "益胃" },
            { "source": "药膳", "target": "养心" },
            { "source": "药膳", "target": "健脾" },
            { "source": "药膳", "target": "益气" },
            { "source": "药膳", "target": "补肝" },
            { "source": "药膳", "target": "强筋" },
            { "source": "药膳", "target": "活血" },
            { "source": "药膳", "target": "益肾" },
            { "source": "药膳", "target": "养血" },
            { "source": "药膳", "target": "益精" },
            { "source": "药膳", "target": "止咳" },
            { "source": "药膳", "target": "解毒" },
            { "source": "药膳", "target": "壮阳" },
            { "source": "药膳", "target": "消肿" },
            { "source": "药膳", "target": "健胃" },
            { "source": "药膳", "target": "利尿" },
            { "source": "药膳", "target": "润燥" },
            { "source": "药膳", "target": "消食" },
            { "source": "药膳", "target": "养阴" },
            { "source": "药膳", "target": "安神" },
            { "source": "药膳", "target": "化痰" },
            { "source": "药膳", "target": "养胃" },
            { "source": "药膳", "target": "壮骨" },
            { "source": "药膳", "target": "免疫" },
            { "source": "药膳", "target": "温胃" },
            { "source": "药膳", "target": "化瘀" },
            { "source": "药膳", "target": "补血" },
            { "source": "药膳", "target": "益肺" },
            { "source": "药膳", "target": "明目" },
            { "source": "药膳", "target": "补虚" },
            { "source": "药膳", "target": "开胃" },
            { "source": "药膳", "target": "固精" },
            { "source": "药膳", "target": "祛痰" },
            { "source": "药膳", "target": "生津" },
            { "source": "药膳", "target": "强身" },
            { "source": "药膳", "target": "和胃" },
            { "source": "药膳", "target": "健骨" },


            { 'source': '健胃', 'target': '栗子淮山猪蹄汤' },
            { 'source': '健胃', 'target': '蜜枣淮山西施骨汤' },
            { 'source': '健胃', 'target': '淮山元肉炖水鱼' },
            { 'source': '健胃', 'target': '芋干瘦肉汤' },
            { 'source': '健脾', 'target': '大地鱼瘦肉滚豆腐汤' },
            { 'source': '健脾', 'target': '红罗卜排骨汤' },
            { 'source': '健脾', 'target': '使君子煲瘦肉汤' },
            { 'source': '健脾', 'target': '眉豆花生玉米煲山斑鱼汤' },
            { 'source': '健脾', 'target': '浮小麦黑豆生蚝汤' },
            { 'source': '健脾', 'target': '五指毛桃煲瘦肉汤' },
            { 'source': '健脾', 'target': '陈皮炖老鸭' },
            { 'source': '健脾', 'target': '山萸肉芡实煲瘦肉' },
            { 'source': '健脾', 'target': '太子参无花果瘦肉汤' },
            { 'source': '健脾', 'target': '百合陈皮鲫鱼汤' },
            { 'source': '健脾', 'target': '糯稻根太子参煲泥鳅鱼汤' },
            { 'source': '健脾', 'target': '沙参玉竹薏仁猪脚筋汤' },
            { 'source': '健脾', 'target': '莲藕鲤鱼汤' },
            { 'source': '健脾', 'target': '核桃淮山芡实猪展汤' },
            { 'source': '健脾', 'target': '莲藕红豆白鸽汤' },
            { 'source': '健脾', 'target': '党参北芪茨实淮山煲瘦肉/山斑鱼汤' },
            { 'source': '健脾', 'target': '淮山党参鹌鹑汤' },
            { 'source': '健脾', 'target': '浮小麦参淮牛展汤' },
            { 'source': '健脾', 'target': '糯稻根煲山斑鱼汤' },
            { 'source': '健脾', 'target': '苹果雪耳瘦肉汤' },
            { 'source': '健脾', 'target': '西洋参淮山红枣清炖乳鸽' },
            { 'source': '健脾', 'target': '花生北芪红枣煲牛展' },
            { 'source': '健脾', 'target': '松子仁煲西洋参鲜鸡汤' },
            { 'source': '健脾', 'target': '石斛玉竹沙参煲瘦肉汤' },
            { 'source': '健脾', 'target': '党参百合煲猪肺' },
            { 'source': '健脾', 'target': '灵芝圆肉煲瘦肉汤' },
            { 'source': '健脾', 'target': '党参百合猪肺' },
            { 'source': '健脾', 'target': '芡实江珧柱猪粉肠汤' },
            { 'source': '健脾', 'target': '无花果茶树菇山鸡汤' },
            { 'source': '健骨', 'target': '杜仲肉菘蓉煲猪骨汤' },
            { 'source': '免疫', 'target': '灵芝圆肉煲瘦肉汤' },
            { 'source': '养心', 'target': '双仁炖猪心汤' },
            { 'source': '养胃', 'target': '鲜莲子滚鸡肉汤' },
            { 'source': '养胃', 'target': '无花果花生煲猪肚汤' },
            { 'source': '养胃', 'target': '沙参玉竹薏仁猪脚筋汤' },
            { 'source': '养血', 'target': '淮山党参鹌鹑汤' },
            { 'source': '养血', 'target': '客家娘酒煲母鸡' },
            { 'source': '养血', 'target': '太子参无花果瘦肉汤' },
            { 'source': '养血', 'target': '浮小麦参淮牛展汤' },
            { 'source': '养血', 'target': '糯稻根煲山斑鱼汤' },
            { 'source': '养血', 'target': '龙利叶黄豆炖白鲫鱼' },
            { 'source': '养血', 'target': '猴头菇白果鲨鱼骨汤' },
            { 'source': '养血', 'target': '西洋参淮山红枣清炖乳鸽' },
            { 'source': '养血', 'target': '花生北芪红枣煲牛展' },
            { 'source': '养血', 'target': '石斛杞子猪肝汤' },
            { 'source': '养血', 'target': '松子仁煲西洋参鲜鸡汤' },
            { 'source': '养血', 'target': '灵芝煲猪肚' },
            { 'source': '养血', 'target': '椰子黄豆无花果田鸡汤' },
            { 'source': '养血', 'target': '榴莲芯煲鲫鱼汤' },
            { 'source': '养血', 'target': '核桃淮山芡实猪展汤' },
            { 'source': '养血', 'target': '党参北芪茨实淮山煲瘦肉/山斑鱼汤' },
            { 'source': '养血', 'target': '黑豆鲤鱼汤' },
            { 'source': '养血', 'target': '大地鱼瘦肉滚豆腐汤' },
            { 'source': '养血', 'target': '荷花荔枝干炖老鸭' },
            { 'source': '养血', 'target': '石斛麦冬瘦肉汽' },
            { 'source': '养血', 'target': '蜜枣淮山西施骨汤' },
            { 'source': '养血', 'target': '杜仲补骨脂排骨汤' },
            { 'source': '养血', 'target': '西洋参石斛淮山煲鸡' },
            { 'source': '养血', 'target': '栗子莲子猪腰汤' },
            { 'source': '养血', 'target': '鸭梨北杏鹅肉汤' },
            { 'source': '养血', 'target': '核桃淡菜番鸭汤' },
            { 'source': '养血', 'target': '冬虫草珧柱猪展汤' },
            { 'source': '养血', 'target': '眉豆花生红枣猪尾汤' },
            { 'source': '养阴', 'target': '淮山沙参玉竹鹅肉汤' },
            { 'source': '养阴', 'target': '鲜莲子滚鸡肉汤' },
            { 'source': '养阴', 'target': '无花果花生煲猪肚汤' },
            { 'source': '利尿', 'target': '猪笼草赤小豆横脷汤' },
            { 'source': '利水', 'target': '春砂仁煲鲫鱼汤' },
            { 'source': '利水', 'target': '白菜干豆腐腊鸭头汤' },
            { 'source': '利水', 'target': '金婴子泽泻煲瘦肉汤' },
            { 'source': '利水', 'target': '莲藕鲤鱼汤' },
            { 'source': '利水', 'target': '莲藕红豆白鸽汤' },
            { 'source': '利水', 'target': '粉葛煲鱼汤' },
            { 'source': '利水', 'target': '豆角干煲鲩鱼尾' },
            { 'source': '利水', 'target': '龙利叶黄豆炖白鲫鱼' },
            { 'source': '利水', 'target': '橄榄响螺瘦肉汤' },
            { 'source': '利水', 'target': '猫爪草煲瘦肉' },
            { 'source': '利水', 'target': '眉豆花生玉米煲山斑鱼汤' },
            { 'source': '利水', 'target': '萝卜滚鳕鱼汤' },
            { 'source': '利湿', 'target': '猪笼草赤小豆横脷汤' },
            { 'source': '利湿', 'target': '白果枝竹冬瓜老鸭汤' },
            { 'source': '利湿', 'target': '春砂仁煲猪肚' },
            { 'source': '利湿', 'target': '黄豆蚝豉排骨苦瓜汤' },
            { 'source': '利湿', 'target': '猫爪草夏枯草煲瘦肉汤' },
            { 'source': '化痰', 'target': '雪梨麻黄瘦肉汤' },
            { 'source': '化痰', 'target': '陈皮炖老鸭' },
            { 'source': '化痰', 'target': '春砂仁煲猪肚' },
            { 'source': '化痰', 'target': '百合陈皮鲫鱼汤' },
            { 'source': '化痰', 'target': '西红柿滚咸猪肉汤' },
            { 'source': '化瘀', 'target': '丹参四鸡炖冰糖' },
            { 'source': '和胃', 'target': '莲藕鲤鱼汤' },
            { 'source': '和胃', 'target': '莲藕红豆白鸽汤' },
            { 'source': '固精', 'target': '栗子淮山猪蹄汤' },
            { 'source': '固肾', 'target': '山萸肉芡实煲瘦肉' },
            { 'source': '壮阳', 'target': '独脚金煲瘦肉' },
            { 'source': '壮阳', 'target': '冬虫草炖水鸭' },
            { 'source': '壮阳', 'target': '栗子莲子猪腰汤' },
            { 'source': '壮阳', 'target': '杜仲肉菘蓉煲猪骨汤' },
            { 'source': '壮阳', 'target': '新鲜霸王花猪展汤' },
            { 'source': '壮阳', 'target': '南北杏煲鳄鱼肉' },
            { 'source': '壮阳', 'target': '清炖蚌肉' },
            { 'source': '壮阳', 'target': '榴莲芯煲鲫鱼汤' },
            { 'source': '壮阳', 'target': '浮小麦黑豆生蚝汤' },
            { 'source': '壮骨', 'target': '杜仲补骨脂排骨汤' },
            { 'source': '安神', 'target': '双仁炖猪心汤' },
            { 'source': '开胃', 'target': '客家娘酒煲母鸡' },
            { 'source': '强筋', 'target': '杜仲补骨脂排骨汤' },
            { 'source': '强筋', 'target': '杜仲肉菘蓉煲猪骨汤' },
            { 'source': '强身', 'target': '杞子滚牛肝汤' },
            { 'source': '明目', 'target': '杞子滚牛肝汤' },
            { 'source': '明目', 'target': '明目补肝汤' },
            { 'source': '止咳', 'target': '百合西洋菜猪展生鱼汤' },
            { 'source': '止咳', 'target': '南北杏煲鳄鱼肉' },
            { 'source': '止咳', 'target': '党参百合煲猪肺' },
            { 'source': '止咳', 'target': '川贝北杏炖鳄鱼肉' },
            { 'source': '止咳', 'target': '党参百合猪肺' },
            { 'source': '止咳', 'target': '川贝枇杷叶炖鳄鱼肉瘦肉汤' },
            { 'source': '止咳', 'target': '无花果茶树菇山鸡汤' },
            { 'source': '止咳', 'target': '核桃淡菜番鸭汤' },
            { 'source': '止咳', 'target': '陈皮炖老鸭' },
            { 'source': '止咳', 'target': '淮山沙参玉竹鹅肉汤' },
            { 'source': '止咳', 'target': '云苓黄精生蚝汤' },
            { 'source': '止咳', 'target': '雪梨麻黄瘦肉汤' },
            { 'source': '止咳', 'target': '红罗卜排骨汤' },
            { 'source': '止咳', 'target': '绿豆百合炖白鸽' },
            { 'source': '止咳', 'target': '鲜茅根霸王花猪肺汤' },
            { 'source': '止咳', 'target': '使君子煲瘦肉汤' },
            { 'source': '止咳', 'target': '椰子黄豆无花果田鸡汤' },
            { 'source': '止咳', 'target': '无花果花生煲猪肚汤' },
            { 'source': '活血', 'target': '丹参四鸡炖冰糖' },
            { 'source': '消肿', 'target': '春砂仁煲鲫鱼汤' },
            { 'source': '消肿', 'target': '白菜干豆腐腊鸭头汤' },
            { 'source': '消肿', 'target': '金婴子泽泻煲瘦肉汤' },
            { 'source': '消肿', 'target': '粉葛煲鱼汤' },
            { 'source': '消肿', 'target': '豆角干煲鲩鱼尾' },
            { 'source': '消肿', 'target': '龙利叶黄豆炖白鲫鱼' },
            { 'source': '消肿', 'target': '橄榄响螺瘦肉汤' },
            { 'source': '消肿', 'target': '猫爪草煲瘦肉' },
            { 'source': '消肿', 'target': '眉豆花生玉米煲山斑鱼汤' },
            { 'source': '消肿', 'target': '猫爪草夏枯草煲瘦肉汤' },
            { 'source': '消肿', 'target': '萝卜滚鳕鱼汤' },
            { 'source': '消食', 'target': '木瓜煲老鸭' },
            { 'source': '消食', 'target': '红罗卜排骨汤' },
            { 'source': '消食', 'target': '使君子煲瘦肉汤' },
            { 'source': '消食', 'target': '眉豆花生玉米煲山斑鱼汤' },
            { 'source': '消食', 'target': '浮小麦黑豆生蚝汤' },
            { 'source': '润燥', 'target': '绵茵陈煲鲫鱼汤' },
            { 'source': '润燥', 'target': '沙参玉竹薏仁猪脚筋汤' },
            { 'source': '润燥', 'target': '清炖蚌肉' },
            { 'source': '润燥', 'target': '沙榄去耳煲猪展汤' },
            { 'source': '润燥', 'target': '竹蔗红罗卜猪骨汤' },
            { 'source': '润燥', 'target': '白菜干豆腐腊鸭头汤' },
            { 'source': '润燥', 'target': '木瓜墨鱼汤' },
            { 'source': '润燥', 'target': '黄芪南枣黄鳝汤' },
            { 'source': '润肺', 'target': '百合西洋菜猪展生鱼汤' },
            { 'source': '润肺', 'target': '南北杏煲鳄鱼肉' },
            { 'source': '润肺', 'target': '党参百合煲猪肺' },
            { 'source': '润肺', 'target': '川贝北杏炖鳄鱼肉' },
            { 'source': '润肺', 'target': '党参百合猪肺' },
            { 'source': '润肺', 'target': '川贝枇杷叶炖鳄鱼肉瘦肉汤' },
            { 'source': '润肺', 'target': '无花果茶树菇山鸡汤' },
            { 'source': '润肺', 'target': '核桃淡菜番鸭汤' },
            { 'source': '润肺', 'target': '客家娘酒煲母鸡' },
            { 'source': '润肺', 'target': '淮山沙参玉竹鹅肉汤' },
            { 'source': '润肺', 'target': '云苓黄精生蚝汤' },
            { 'source': '润肺', 'target': '雪梨麻黄瘦肉汤' },
            { 'source': '润肺', 'target': '红罗卜排骨汤' },
            { 'source': '润肺', 'target': '绿豆百合炖白鸽' },
            { 'source': '润肺', 'target': '鲜茅根霸王花猪肺汤' },
            { 'source': '润肺', 'target': '使君子煲瘦肉汤' },
            { 'source': '润肺', 'target': '椰子黄豆无花果田鸡汤' },
            { 'source': '润肺', 'target': '无花果花生煲猪肚汤' },
            { 'source': '润肺', 'target': '西红柿滚咸猪肉汤' },
            { 'source': '润肺', 'target': '苹果雪耳瘦肉汤' },
            { 'source': '润肺', 'target': '鲜橄榄煲海螺瘦肉汤' },
            { 'source': '润肺', 'target': '荷花荔枝干炖老鸭' },
            { 'source': '润肺', 'target': '石斛淮山杞子猪骨汤' },
            { 'source': '润肺', 'target': '石斛冰糖茶' },
            { 'source': '润肺', 'target': '石斛麦冬瘦肉汽' },
            { 'source': '润肺', 'target': '石斛太子参煲瘦肉' },
            { 'source': '润肺', 'target': '石斛玉竹沙参煲瘦肉汤' },
            { 'source': '润肺', 'target': '淮山莲子煲海龙' },
            { 'source': '润肺', 'target': '毛冬青杞子菟丝子煲瘦肉汤' },
            { 'source': '润肺', 'target': '西洋参石斛淮山煲鸡' },
            { 'source': '润肺', 'target': '鸭梨北杏鹅肉汤' },
            { 'source': '润肺', 'target': '原盅炖北菇' },
            { 'source': '润肺', 'target': '清补凉乳鸽汤' },
            { 'source': '润肺', 'target': '木瓜煲老鸭' },
            { 'source': '润肺', 'target': '冬虫草炖水鸭' },
            { 'source': '润肺', 'target': '猴头菇白果鲨鱼骨汤' },
            { 'source': '润肺', 'target': '白果枝竹冬瓜老鸭汤' },
            { 'source': '润肺', 'target': '蜜瓜海螺老鸡汤' },
            { 'source': '清热', 'target': '清补凉乳鸽汤' },
            { 'source': '清热', 'target': '春砂仁煲猪肚' },
            { 'source': '清热', 'target': '粉葛煲鱼汤' },
            { 'source': '清热', 'target': '豆角干煲鲩鱼尾' },
            { 'source': '清热', 'target': '雪梨麻黄瘦肉汤' },
            { 'source': '清热', 'target': '黄豆蚝豉排骨苦瓜汤' },
            { 'source': '清热', 'target': '绿豆百合炖白鸽' },
            { 'source': '清热', 'target': '荷花荔枝干炖老鸭' },
            { 'source': '清热', 'target': '橄榄响螺瘦肉汤' },
            { 'source': '清热', 'target': '鲜茅根霸王花猪肺汤' },
            { 'source': '清热', 'target': '猫爪草煲瘦肉' },
            { 'source': '清热', 'target': '西红柿滚咸猪肉汤' },
            { 'source': '清热', 'target': '猫爪草夏枯草煲瘦肉汤' },
            { 'source': '清热', 'target': '莲藕鲤鱼汤' },
            { 'source': '清热', 'target': '莲藕红豆白鸽汤' },
            { 'source': '清热', 'target': '萝卜滚鳕鱼汤' },
            { 'source': '清热', 'target': '白果枝竹冬瓜老鸭汤' },
            { 'source': '清热', 'target': '蜜瓜海螺老鸡汤' },
            { 'source': '清热', 'target': '百合陈皮鲫鱼汤' },
            { 'source': '清热', 'target': '明目补肝汤' },
            { 'source': '清热', 'target': '百合西洋菜猪展生鱼汤' },
            { 'source': '清热', 'target': '春砂仁煲鲫鱼汤' },
            { 'source': '清热', 'target': '猪笼草赤小豆横脷汤' },
            { 'source': '清热', 'target': '绵茵陈煲鲫鱼汤' },
            { 'source': '清热', 'target': '金婴子泽泻煲瘦肉汤' },
            { 'source': '清热', 'target': '鲜橄榄煲海螺瘦肉汤' },
            { 'source': '清热', 'target': '川贝北杏炖鳄鱼肉' },
            { 'source': '清热', 'target': '川贝枇杷叶炖鳄鱼肉瘦肉汤' },
            { 'source': '清热', 'target': '丹参四鸡炖冰糖' },
            { 'source': '清热', 'target': '原盅炖北菇' },
            { 'source': '清热', 'target': '竹蔗红罗卜猪骨汤' },
            { 'source': '温胃', 'target': '芡实江珧柱猪粉肠汤' },
            { 'source': '温胃', 'target': '山萸肉芡实煲瘦肉' },
            { 'source': '温胃', 'target': '糯稻根太子参煲泥鳅鱼汤' },
            { 'source': '滋阴', 'target': '淮山党参鹌鹑汤' },
            { 'source': '滋阴', 'target': '太子参无花果瘦肉汤' },
            { 'source': '滋阴', 'target': '绵茵陈煲鲫鱼汤' },
            { 'source': '滋阴', 'target': '百合陈皮鲫鱼汤' },
            { 'source': '滋阴', 'target': '沙参玉竹薏仁猪脚筋汤' },
            { 'source': '滋阴', 'target': '苹果雪耳瘦肉汤' },
            { 'source': '滋阴', 'target': '鲜橄榄煲海螺瘦肉汤' },
            { 'source': '滋阴', 'target': '石斛淮山杞子猪骨汤' },
            { 'source': '滋阴', 'target': '石斛冰糖茶' },
            { 'source': '滋阴', 'target': '石斛麦冬瘦肉汽' },
            { 'source': '滋阴', 'target': '石斛太子参煲瘦肉' },
            { 'source': '滋阴', 'target': '明目补肝汤' },
            { 'source': '滋阴', 'target': '石斛杞子猪肝汤' },
            { 'source': '滋阴', 'target': '清炖蚌肉' },
            { 'source': '滋阴', 'target': '石斛玉竹沙参煲瘦肉汤' },
            { 'source': '滋阴', 'target': '椰子黄豆无花果田鸡汤' },
            { 'source': '滋阴', 'target': '淮山莲子煲海龙' },
            { 'source': '滋阴', 'target': '毛冬青杞子菟丝子煲瘦肉汤' },
            { 'source': '滋阴', 'target': '沙榄去耳煲猪展汤' },
            { 'source': '滋阴', 'target': '西洋参石斛淮山煲鸡' },
            { 'source': '滋阴', 'target': '竹蔗红罗卜猪骨汤' },
            { 'source': '滋阴', 'target': '鸭梨北杏鹅肉汤' },
            { 'source': '滋阴', 'target': '原盅炖北菇' },
            { 'source': '滋阴', 'target': '冬虫草珧柱猪展汤' },
            { 'source': '滋阴', 'target': '五指毛桃煲瘦肉汤' },
            { 'source': '滋阴', 'target': '清补凉乳鸽汤' },
            { 'source': '滋阴', 'target': '白菜干豆腐腊鸭头汤' },
            { 'source': '滋阴', 'target': '木瓜煲老鸭' },
            { 'source': '滋阴', 'target': '黑豆鲤鱼汤' },
            { 'source': '滋阴', 'target': '木瓜墨鱼汤' },
            { 'source': '滋阴', 'target': '大地鱼瘦肉滚豆腐汤' },
            { 'source': '滋阴', 'target': '冬虫草炖水鸭' },
            { 'source': '滋阴', 'target': '猴头菇白果鲨鱼骨汤' },
            { 'source': '滋阴', 'target': '杜仲补骨脂排骨汤' },
            { 'source': '滋阴', 'target': '栗子莲子猪腰汤' },
            { 'source': '滋阴', 'target': '黄芪南枣黄鳝汤' },
            { 'source': '滋阴', 'target': '核桃淡菜番鸭汤' },
            { 'source': '滋阴', 'target': '白果枝竹冬瓜老鸭汤' },
            { 'source': '滋阴', 'target': '蜜瓜海螺老鸡汤' },
            { 'source': '滋阴', 'target': '眉豆花生红枣猪尾汤' },
            { 'source': '滋阴', 'target': '芋干瘦肉汤' },
            { 'source': '理气', 'target': '陈皮炖老鸭' },
            { 'source': '生津', 'target': '鲜莲子滚鸡肉汤' },
            { 'source': '益气', 'target': '龙利叶黄豆炖白鲫鱼' },
            { 'source': '益气', 'target': '猴头菇白果鲨鱼骨汤' },
            { 'source': '益气', 'target': '黄芪南枣黄鳝汤' },
            { 'source': '益气', 'target': '眉豆花生红枣猪尾汤' },
            { 'source': '益气', 'target': '苹果雪耳瘦肉汤' },
            { 'source': '益气', 'target': '鲜莲子滚鸡肉汤' },
            { 'source': '益气', 'target': '荷花荔枝干炖老鸭' },
            { 'source': '益气', 'target': '党参百合煲猪肺' },
            { 'source': '益气', 'target': '灵芝圆肉煲瘦肉汤' },
            { 'source': '益气', 'target': '党参百合猪肺' },
            { 'source': '益气', 'target': '鸭梨北杏鹅肉汤' },
            { 'source': '益气', 'target': '芋干瘦肉汤' },
            { 'source': '益气', 'target': '冬虫草珧柱猪展汤' },
            { 'source': '益气', 'target': '双仁炖猪心汤' },
            { 'source': '益气', 'target': '核桃淮山芡实猪展汤' },
            { 'source': '益精', 'target': '山萸肉芡实煲瘦肉' },
            { 'source': '益精', 'target': '黑豆鲤鱼汤' },
            { 'source': '益精', 'target': '木瓜墨鱼汤' },
            { 'source': '益精', 'target': '糯稻根太子参煲泥鳅鱼汤' },
            { 'source': '益精', 'target': '云苓黄精生蚝汤' },
            { 'source': '益精', 'target': '独脚金煲瘦肉' },
            { 'source': '益精', 'target': '石斛淮山杞子猪骨汤' },
            { 'source': '益精', 'target': '石斛冰糖茶' },
            { 'source': '益精', 'target': '淮山莲子煲海龙' },
            { 'source': '益精', 'target': '毛冬青杞子菟丝子煲瘦肉汤' },
            { 'source': '益精', 'target': '新鲜霸王花猪展汤' },
            { 'source': '益肝', 'target': '五指毛桃煲瘦肉汤' },
            { 'source': '益肝', 'target': '明目补肝汤' },
            { 'source': '益肺', 'target': '浮小麦参淮牛展汤' },
            { 'source': '益肺', 'target': '竹蔗红罗卜猪骨汤' },
            { 'source': '益肺', 'target': '太子参无花果瘦肉汤' },
            { 'source': '益肾', 'target': '新鲜霸王花猪展汤' },
            { 'source': '益肾', 'target': '大地鱼瘦肉滚豆腐汤' },
            { 'source': '益肾', 'target': '杞子滚牛肝汤' },
            { 'source': '益肾', 'target': '栗子淮山猪蹄汤' },
            { 'source': '益肾', 'target': '南北杏煲鳄鱼肉' },
            { 'source': '益肾', 'target': '糯稻根煲山斑鱼汤' },
            { 'source': '益肾', 'target': '西洋参淮山红枣清炖乳鸽' },
            { 'source': '益肾', 'target': '花生北芪红枣煲牛展' },
            { 'source': '益肾', 'target': '石斛杞子猪肝汤' },
            { 'source': '益肾', 'target': '松子仁煲西洋参鲜鸡汤' },
            { 'source': '益肾', 'target': '蜜枣淮山西施骨汤' },
            { 'source': '益肾', 'target': '淮山元肉炖水鱼' },
            { 'source': '益肾', 'target': '榴莲芯煲鲫鱼汤' },
            { 'source': '益肾', 'target': '沙榄去耳煲猪展汤' },
            { 'source': '益肾', 'target': '芡实江珧柱猪粉肠汤' },
            { 'source': '益肾', 'target': '浮小麦黑豆生蚝汤' },
            { 'source': '益肾', 'target': '无花果茶树菇山鸡汤' },
            { 'source': '益肾', 'target': '石斛太子参煲瘦肉' },
            { 'source': '益肾', 'target': '党参北芪茨实淮山煲瘦肉/山斑鱼汤' },
            { 'source': '益胃', 'target': '木瓜煲老鸭' },
            { 'source': '祛痰', 'target': '黄豆蚝豉排骨苦瓜汤' },
            { 'source': '补气', 'target': '客家娘酒煲母鸡' },
            { 'source': '补气', 'target': '浮小麦参淮牛展汤' },
            { 'source': '补气', 'target': '淮山沙参玉竹鹅肉汤' },
            { 'source': '补气', 'target': '糯稻根煲山斑鱼汤' },
            { 'source': '补气', 'target': '西洋参淮山红枣清炖乳鸽' },
            { 'source': '补气', 'target': '花生北芪红枣煲牛展' },
            { 'source': '补气', 'target': '松子仁煲西洋参鲜鸡汤' },
            { 'source': '补气', 'target': '灵芝煲猪肚' },
            { 'source': '补气', 'target': '榴莲芯煲鲫鱼汤' },
            { 'source': '补气', 'target': '党参北芪茨实淮山煲瘦肉/山斑鱼汤' },
            { 'source': '补气', 'target': '淮山党参鹌鹑汤' },
            { 'source': '补气', 'target': '石斛太子参煲瘦肉' },
            { 'source': '补气', 'target': '石斛玉竹沙参煲瘦肉汤' },
            { 'source': '补气', 'target': '西洋参石斛淮山煲鸡' },
            { 'source': '补肝', 'target': '杞子滚牛肝汤' },
            { 'source': '补肝', 'target': '石斛杞子猪肝汤' },
            { 'source': '补肾', 'target': '独脚金煲瘦肉' },
            { 'source': '补肾', 'target': '黑豆鲤鱼汤' },
            { 'source': '补肾', 'target': '木瓜墨鱼汤' },
            { 'source': '补肾', 'target': '糯稻根太子参煲泥鳅鱼汤' },
            { 'source': '补肾', 'target': '云苓黄精生蚝汤' },
            { 'source': '补肾', 'target': '冬虫草炖水鸭' },
            { 'source': '补肾', 'target': '栗子莲子猪腰汤' },
            { 'source': '补肾', 'target': '核桃淮山芡实猪展汤' },
            { 'source': '补肾', 'target': '杜仲肉菘蓉煲猪骨汤' },
            { 'source': '补肾', 'target': '冬虫草珧柱猪展汤' },
            { 'source': '补肾', 'target': '石斛淮山杞子猪骨汤' },
            { 'source': '补肾', 'target': '石斛冰糖茶' },
            { 'source': '补肾', 'target': '石斛麦冬瘦肉汽' },
            { 'source': '补肾', 'target': '清炖蚌肉' },
            { 'source': '补肾', 'target': '淮山莲子煲海龙' },
            { 'source': '补肾', 'target': '毛冬青杞子菟丝子煲瘦肉汤' },
            { 'source': '补脾', 'target': '栗子淮山猪蹄汤' },
            { 'source': '补脾', 'target': '鲜莲子滚鸡肉汤' },
            { 'source': '补脾', 'target': '蜜枣淮山西施骨汤' },
            { 'source': '补脾', 'target': '淮山元肉炖水鱼' },
            { 'source': '补脾', 'target': '无花果花生煲猪肚汤' },
            { 'source': '补脾', 'target': '芡实江珧柱猪粉肠汤' },
            { 'source': '补脾', 'target': '芋干瘦肉汤' },
            { 'source': '补脾', 'target': '眉豆花生红枣猪尾汤' },
            { 'source': '补虚', 'target': '新鲜霸王花猪展汤' },
            { 'source': '补血', 'target': '黄芪南枣黄鳝汤' },
            { 'source': '补血', 'target': '双仁炖猪心汤' },
            { 'source': '解毒', 'target': '清补凉乳鸽汤' },
            { 'source': '解毒', 'target': '春砂仁煲猪肚' },
            { 'source': '解毒', 'target': '粉葛煲鱼汤' },
            { 'source': '解毒', 'target': '豆角干煲鲩鱼尾' },
            { 'source': '解毒', 'target': '黄豆蚝豉排骨苦瓜汤' },
            { 'source': '解毒', 'target': '绿豆百合炖白鸽' },
            { 'source': '解毒', 'target': '橄榄响螺瘦肉汤' },
            { 'source': '解毒', 'target': '鲜茅根霸王花猪肺汤' },
            { 'source': '解毒', 'target': '猫爪草煲瘦肉' },
            { 'source': '解毒', 'target': '西红柿滚咸猪肉汤' },
            { 'source': '解毒', 'target': '猫爪草夏枯草煲瘦肉汤' },
            { 'source': '解毒', 'target': '萝卜滚鳕鱼汤' },
            { 'source': '解毒', 'target': '蜜瓜海螺老鸡汤' },
            { 'source': '解毒', 'target': '百合西洋菜猪展生鱼汤' },
            { 'source': '解毒', 'target': '春砂仁煲鲫鱼汤' },
            { 'source': '解毒', 'target': '猪笼草赤小豆横脷汤' },
            { 'source': '解毒', 'target': '绵茵陈煲鲫鱼汤' },
            { 'source': '解毒', 'target': '金婴子泽泻煲瘦肉汤' },
            { 'source': '解毒', 'target': '鲜橄榄煲海螺瘦肉汤' },
            { 'source': '解毒', 'target': '川贝北杏炖鳄鱼肉' },
            { 'source': '解毒', 'target': '川贝枇杷叶炖鳄鱼肉瘦肉汤' },
            { 'source': '解毒', 'target': '丹参四鸡炖冰糖' },
            { 'source': '解毒', 'target': '原盅炖北菇' }





            ],
            focusNodeAdjacency: true,
            roam: true,
            label: {
                normal: {

                    show: true,
                    position: 'top',

                }
            },
            lineStyle: {
                normal: {
                    color: 'source',
                    curveness: 0,
                    type: "solid",
                    width: 1,
                }
            },
            roam: true,  // 允许缩放和拖动
            scaleLimit: {
                min: 0.5,  // 最小缩放比例
                max: 2  // 最大缩放比例
            },
            initialScale: 10  // 初始缩放比例
        }]
    };
    myChart.setOption(option)

    myChart.on('click', function (params) {
        if (params.dataType === 'node') {
            var YSname = params.data.name;
            window.location.href = '药膳搜索.html?YSname=' + YSname;
        }
    });

})()